name: more_visibility_example
description: Example showcasing more_visibility custom lint.
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  more_visibility_annotation: ^0.1.1

dev_dependencies:
  lints: ^6.0.0
  more_visibility: ^0.1.2
  test: ^1.28.0
