name: more_visibility_example
description: Example showcasing more_visibility custom lint.
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  more_visibility_annotation: ^0.1.1
  riverpod_annotation: ^3.0.3

dev_dependencies:
  build_runner: ^2.10.4
  lints: ^6.0.0
  more_visibility:
    path: ../
  riverpod_generator: ^3.0.3
  test: ^1.28.0


