name: more_visibility_example
description: Example showcasing more_visibility custom lint.
version: 0.0.1

environment:
  sdk: ^3.9.2

dependencies:
  more_visibility: ^0.1.0

dev_dependencies:
  custom_lint: any
  more_visibility: ^0.1.0
