name: dartv
description: Static visibility analyzer for Dart that enforces protected and package-private style boundaries.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  analyzer: ^6.4.1
  args: ^2.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  dartv: dartv
