name: more_visibility
description: "Custom lint and builder bringing directory-scoped visibility via @mprotected and @mdefault annotations."
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  analyzer: ^6.4.1
  build: ^2.3.1
  args: ^2.5.0
  path: ^1.9.0
  custom_lint_builder: ^0.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  custom_lint: ^0.6.0
  build_runner: ^2.4.13

