name: more_visibility
description: "Analysis server plugin and builder bringing directory-scoped visibility via @mprotected and @mdefault annotations."
version: 0.1.10
repository: https://github.com/Harineko0/more_visibility

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  analyzer: ^8.0.0
  analysis_server_plugin: ^0.3.0
  build: ^4.0.3
  args: ^2.7.0
  path: ^1.9.1
  more_visibility_annotation: ^0.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  build_runner: ^2.10.4
