name: more_visibility
description: "Custom lint and builder bringing directory-scoped visibility via @mprotected and @mdefault annotations."
version: 0.1.3
repository: https://github.com/Harineko0/more_visibility

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  analyzer: ^8.0.0
  build: ^4.0.3
  args: ^2.7.0
  path: ^1.9.1
  custom_lint_builder: ^0.8.1
  more_visibility_annotation: ^0.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  custom_lint: ^0.8.1
  build_runner: ^2.10.4
