name: more_visibility_annotation
description: "Annotations for more_visibility package."
version: 0.1.0
repository: https://github.com/Harineko0/more_visibility_annotation

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
