name: more_visibility_annotation
description: "Annotations for more_visibility package."
version: 0.1.2
repository: https://github.com/Harineko0/more_visibility_annotation

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
